name: Plugin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: go.mod
      - name: Validate plugin structure
        run: make plugin-check
      - name: Smoke test plugin runtime
        run: make plugin-smoke
